name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [7.2.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --no-audit --no-fund || true
        ./node_modules/.bin/hexo generate

    - name: Deploy to daijunoo pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}  # 使用相同的 PAT
        repository-name: daijunooo/daijunooo.github.com
        branch: master
        folder: public
