name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [7.2.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --no-audit --no-fund || true
        ./node_modules/.bin/hexo generate && cd ./public && ls -la

    - name: Deploy to daijunoo pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.token }}
        publish_dir: ./public
        external_repository: daijunooo/daijunooo.github.io  # 目标仓库
        publish_branch: master  # GitHub Pages 默认分支
